In [ ]:
getwd()

In [ ]:
library(data.table)

In [ ]:
apartments <- fread("https://gist.githubusercontent.com/pbeens/2fd6834d3cc657730300e8dfb1d8cfb1/raw/a1e6f63d0028dc8f9c3800249bc6bb0227ea115a/apartments-for-rent-2019.csv")

In [ ]:
apartments

In [ ]:
apartments[ square_feet < 500 & price < 500 ,
          .(id, title , cityname, price, annual_price = price * 12) ]

In [ ]:
apartments[ square_feet < 500 & price < 500 ]
â€‹
apartments[ square_feet < 500 & price < 500 ,
        annual_price := price * 12 ]
apartments[ square_feet < 500 & price < 500 ,]

In [ ]:
apartments[, .(max_squarefeet = max(square_feet, na.rm = T), avg_price = mean(price, na.rm = T)),
        by = c("cityname", "state")]

apartments_at<- apartments[, .(max_squarefeet = max(square_feet, na.rm = T), avg_price = mean(price, na.rm = T)),
        by = c("cityname", "state")]

In [ ]:
apartments_at_wide <- dcast(apartments_at,state ~ cityname  , value.var = "avg_price")

apartments_at_wide

In [ ]:

melt(apartments_at_wide, id.vars = "state", variable.name = "origin2", value.name = "av_price2")